<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Gci.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="providers.default.json" LogicalName="Gci.Core.providers.default.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Gci.Core.Tests" />
  </ItemGroup>

</Project>
